version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: cimg-publishing

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Images"
          command: |
            ./build-images.sh
            docker images
            echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
      - run:
          name: "Install Test Prerequisites"
          command: apk add mysql-client
      - run: 
          name: "Test Docker Images"
          shell: /bin/bash -o pipefail
          command: |
            ssh -f -N -L localhost:3306:localhost:3306 remote-docker
            IMAGES=$(docker images --format='{{.Repository}}:{{.Tag}}' | grep -Eo "cimg/mysql:[0-9]+\.[0-9]+\.[0-9]+")
            for IMAGE in $IMAGES; do
              printf "Booting $IMAGE...\n"
              CONTAINER_ID=$(docker run --rm --env MYSQL_USER=user --env MYSQL_PASSWORD=passw0rd -p 3306:3306 -d $IMAGE)
              for i in {1..20}; do
                printf "[$i/20] Checking MySQL is up...\n"
                mysqladmin ping -h 127.0.0.1 --silent
                if [ $? -eq 0 ]; then
                  printf "Booted $IMAGE!\n"
                  break
                elif [ $? -ne 0 ] && [ $i -eq 36 ]; then
                  printf "Failed to boot image\n"
                  exit 1
                fi
                printf "[$i/20] No response. Sleeping 10s...\n"
                sleep 10s
              done
              printf "Running Test Command...\n"
              mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT VERSION();"
              printf "Stopping $IMAGE...\n"
              docker stop $CONTAINER_ID >/dev/null 2>&1
            done
            printf "All images passed!\n"

      - deploy:
          name: "Publish Docker Images (main branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              
              echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing cimg/mysql to Docker Hub production."
                docker push cimg/mysql
              else
                echo "Skipping publishing."
              fi
              # Update the Docker Hub description
              STUBB_VER=0.2.0
              STUBB_URL="https://github.com/CircleCI-Public/stubb/releases/download/v${STUBB_VER}/stubb_${STUBB_VER}-linux-amd64.tar.gz"
              curl -sSL $STUBB_URL | tar -xz -C /usr/local/bin stubb
              stubb set description cimg/mysql ./README.md
            fi
